### ISSUE TITLE
Add WebP library and gdk-pixbuf loader

### ISSUE THREAD

**Issue by hadess** [flathub/org.gnome.Evince#10]
So that WebP web-comics can be loaded, see:
https://gitlab.gnome.org/GNOME/evince/issues/925

**Comment by hadess** [comment]
The patch I ended up using:
https://gitlab.gnome.org/GNOME/evince/merge_requests/50
should be easy to adapt for the stable version.

**Comment by nedrichards** [comment]
This is in the 3.30 version, right?

**Comment by nedrichards** [comment]
Hrm, I didn't manage to make this work with the obvious adaptation. In my 3.30 test :-(

**Comment by hadess** [comment]
> This is in the 3.30 version, right?

It's a Flatpak-specific change, I don't think I needed to change anything in evince itself, though I was only testing with master at the time, and I added some better error reporting that shouldn't impact this.

This MR doesn't include the gdk-pixbuf-loader for WebP in the Flatpak:
https://github.com/flathub/org.gnome.Evince/pull/11
is this what you tested?

**Comment by nedrichards** [comment]
I tested it locally before I pushed the PR and it didn't load the sample webp file from the webp site so I removed it from the PR.

**Comment by hadess** [comment]
> I tested it locally before I pushed the PR and it didn't load the sample webp file from the webp site so I removed it from the PR.

It doesn't load *webp files*, it loads *webp comics*. So a ZIP file with sequentially named webp files, renamed to cbz, should work. There's an example CBZ with webp contents in the original issue:
https://gitlab.gnome.org/GNOME/evince/issues/925

**Comment by hadess** [comment]
I got the webp comics support to work with the current 3.28 evince, want me to try again with your 3.30 evince, or is it a matter of you using the wrong test? :)

This is the patch I used:
[webp.txt](https://github.com/flathub/org.gnome.Evince/files/2383516/webp.txt)
