### ISSUE TITLE
Error registering document

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.gnome.Evince#12]
I get this error opening files in Evince 3.30:

> Error registering document: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown

Running:

> flatpak run --log-session-bus org.gnome.Evince

It seems to be with failing to launch the Evince Daemon. Maybe some more permissions needed here.

**Comment by hadess** [comment]
```
  68 #define APPLICATION_NAME             "org.gnome.Evince"•
  72 #define EVINCE_DAEMON_SERVICE        "org.gnome.evince.Daemon"•
```

I think those should probably have the same case so they're considered part of the same application.

**Comment by nedrichards** [comment]
That would be correct!

**Comment by hadess** [comment]
Filed https://gitlab.gnome.org/GNOME/evince/issues/990

**Comment by hadess** [comment]
And patches:
https://gitlab.gnome.org/GNOME/evince/merge_requests/86
https://gitlab.gnome.org/GNOME/evince/merge_requests/87

Note that I needed to use:
```
"rm-configure" : true,
```
in evince for autoreconf to work.
