### ISSUE TITLE
Evince still on version 43.1 on flathub

### ISSUE THREAD

**Issue by rfrohl** [flathub/org.gnome.Evince#124]
Hi,

not sure if this is the right place to ask: I see that the repo was updated to version 44, but that version did not make it to flathub yet [0]. Any idea what the issue might be ?

Thanks!

[0] https://flathub.org/apps/org.gnome.Evince

**Comment by A6GibKm** [comment]
It is on 44.1, its just the metainfo of the app being wrong, see the about dialog of the app.
