### ISSUE TITLE
Segmentation fault (core dumped) when opening pdf file

### ISSUE THREAD

**Issue by empiretylh** [flathub/org.gnome.Evince#135]
My Ubuntu 22.02 has issue with evince pdf document viewer, 
when i open with pdf files with this command 
`evince *****.pdf`

the pdf file has not open and show this error
`Segmentation fault (core dumped)`

**Comment by hfiguiere** [comment]
`evince *****.pdf` mean that it is not the flaptak but the package from the distribution.

**Comment by gpoo** [comment]
Please file a bug in https://gitlab.gnome.org/GNOME/Evince/issues and attach or link a test case.
