### ISSUE TITLE
can't install evince in opensuse leap 15

### ISSUE THREAD

**Issue by marcosps** [flathub/org.gnome.Evince#17]
When trying to execute flatpak install in my opensuse leap, this problem happens:

Required runtime for org.gnome.Evince/x86_64/stable (org.gnome.Platform/x86_64/3.30) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]: y
Installing: org.gnome.Platform/x86_64/3.30 from flathub
[####################] 10 delta parts, 29 loose fetched; 162421 KiB transferred in 86 seconds
Installing: org.gnome.Platform.Locale/x86_64/3.30 from flathub
[####################] 6 delta parts, 1 loose fetched; 28861 KiB transferred in 31 seconds
Installing: org.gnome.Evince/x86_64/stable from flathub
[####################] 1 delta parts, 3 loose fetched; 4784 KiB transferred in 6 seconds
(flatpak install:137538): flatpak-WARNING **: Non-prefixed filename org.gnome.evince.Daemon.service in app org.gnome.Evince, removing.

Is this a known issue?

**Comment by hadess** [comment]
@gpoo Why don't we still have this sorted in the 3.30 branch?

**Comment by gpoo** [comment]
Try again once 3.30.2 lands in flathub.

**Comment by hadess** [comment]
> Try again once 3.30.2 lands in flathub.

Tested locally from those sources, and it works, thanks.

**Comment by marcosps** [comment]
I have a new machine with Leap 15, and the same problem is still happening:

```sh
Installing: org.gnome.Evince/x86_64/stable from flathub
[####################] 1 metadata, 0 content objects fetched; 569 B transferred in 0 seconds
(flatpak install:20501): flatpak-WARNING **: Non-prefixed filename org.gnome.evince.Daemon.service in app org.gnome.Evince, removing.

error: No such file or directory
```

**Comment by gpoo** [comment]
@marcops: And which version is trying to install?

**Comment by marcosps** [comment]
The problem does not appear anymore once Leap 15.1 beta was released, so I think this problem was related to flatpak version shipped in Leap 15. Sorry for the noise.
