### ISSUE TITLE
Missing fonts

### ISSUE THREAD

**Issue by Zlopez** [flathub/org.gnome.Evince#21]
I tried to open a document and none of the fonts was available in the flatpak, so I end up with unreadable text.
It's possible to read them from some runtime?

**Unreadable text in czech sample**:
![screenshot from 2019-03-03 16-57-38](https://user-images.githubusercontent.com/6943409/53697807-8c23de00-3dd5-11e9-877b-35cf5bc310b5.png)

**Output of Properties->Fonts**:
![screenshot from 2019-03-03 16-57-54](https://user-images.githubusercontent.com/6943409/53697808-904ffb80-3dd5-11e9-8d70-ffdf2c128a1e.png)

**Comment by TingPing** [comment]
Your unreadable example looks like an encoding issue not a font issue.

**Comment by Zlopez** [comment]
This PDF doesn't have embeded fonts, but it's correctly displayed in gmail web interface. So I think this is issue with fonts, otherwise this issue will be same in every other PDF reader.

Sent from ProtonMail mobile

-------- Původní zpráva --------
Zapnuto 3. 3. 2019 18:47, Patrick napsal:

**Comment by TingPing** [comment]
That is faulty logic. The characters are rendered just the wrong ones which is an encoding issue, otherwise they would show as the missing font character. That isn't to say it isn't an Evince bug.

**Comment by Zlopez** [comment]
Ok, in this case where should I fill the bug?

Sent from ProtonMail mobile

-------- Původní zpráva --------
Zapnuto 3. 3. 2019 19:50, Patrick napsal:

**Comment by jascrain** [comment]
> Ok, in this case where should I fill the bug?

It could be a problem with poppler, the library evince uses for PDF rendering. Try it with poppler's pdftocairo program, such as `pdftocairo -png input.pdf output`, and if it's the same bad rendering, file a bug at https://gitlab.freedesktop.org/poppler/poppler/issues/new?issue .

**Comment by Zlopez** [comment]
@jascrain Thanks, I tried the `pdftocairo` and got different bad rendering, but still it was rendered badly. So I created an [issue](https://gitlab.freedesktop.org/poppler/poppler/issues/734) in poppler. I hope this will be useful.

**Comment by gpoo** [comment]
Closing this issue, as it belongs to Poppler.
