### ISSUE TITLE
Printing issue: some options missing

### ISSUE THREAD

**Issue by Enaunimes** [flathub/org.gnome.Evince#22]
While printing with Evince running inside flatpak environment, the Page Handling tab is missing. It is also impossible to scale the page under Page Setup.

See in the pictures:
![Scalable](https://user-images.githubusercontent.com/19330120/54266999-6657bf80-45b3-11e9-8c8a-3d1b3d73e184.png)
![Not Scalable](https://user-images.githubusercontent.com/19330120/54267001-66f05600-45b3-11e9-98d0-f1f8e6dcdcb0.png)

**Comment by jascrain** [comment]
The "Page Handling" tab is missing because it's a custom widget and Gtk's printing portal does not support custom widgets.

**Comment by Enaunimes** [comment]
> The "Page Handling" tab is missing because it's a custom widget and Gtk's printing portal does not support custom widgets.

Thanks for the explanation. 
Any idea why the scaling not working?

**Comment by hadess** [comment]
Can you please attach the screenshots to this issue rather than on a ad-ridden website? Thanks.

**Comment by Enaunimes** [comment]
> Can you please attach the screenshots to this issue rather than on a ad-ridden website? Thanks.

Here you go: https://chaoticvoid.net/share/Scalable.png    https://chaoticvoid.net/share/Not.Scalable.png

**Comment by Enaunimes** [comment]
> Can you please attach the screenshots to this issue rather than on a ad-ridden website? Thanks.

Didn't know I can upload image. Here they are:
![Scalable](https://user-images.githubusercontent.com/19330120/54266999-6657bf80-45b3-11e9-8c8a-3d1b3d73e184.png)
![Not Scalable](https://user-images.githubusercontent.com/19330120/54267001-66f05600-45b3-11e9-98d0-f1f8e6dcdcb0.png)

**Comment by gpoo** [comment]
The upstream issue is https://gitlab.gnome.org/GNOME/evince/issues/1015
