### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by ghost** [flathub/org.gnome.Evince#24]
I'm on Fedora Silverblue 30 and I'm having an issue with PDF thumbnails. Simply they are not being generated due to confinement. Is there a way, such as a command or extension, to allow this?

I have opted to install "Evince" via rpm-ostree for the time being because I simply have too many documents to search through and it helps to have that visual.

**Comment by teohhanhui** [comment]
I see that the thumbnailer is disabled in the build: https://github.com/flathub/org.gnome.Evince/blob/6457d1c6c63ceca03487c67ec5522caa10d71730/org.gnome.Evince.json#L182

Is there a reason why? Otherwise I'd think it's possible to just create `~/.local/share/thumbnailers/evince.thumbnailer`:

```
[Thumbnailer Entry]
#TryExec=evince-thumbnailer
Exec=flatpak run --command=evince-thumbnailer org.gnome.Evince -s %s %u %o
MimeType=application/vnd.comicbook-rar;application/vnd.comicbook+zip;application/x-cb7;application/x-cbr;application/x-cbt;application/x-cbz;application/x-ext-cb7;application/x-ext-cbr;application/x-ext-cbt;application/x-ext-cbz;application/x-ext-djv;application/x-ext-djvu;image/vnd.djvu+multipage;application/x-bzdvi;application/x-dvi;application/x-ext-dvi;application/x-gzdvi;application/pdf;application/x-bzpdf;application/x-ext-pdf;application/x-gzpdf;application/x-xzpdf;application/postscript;application/x-bzpostscript;application/x-gzpostscript;application/x-ext-eps;application/x-ext-ps;image/x-bzeps;image/x-eps;image/x-gzeps;image/tiff;application/oxps;application/vnd.ms-xpsdocument;application/illustrator
```

**Comment by Froggy232** [comment]
Hi,
Does someone have found a solution?
I tried teohhanhui one, but it doesn't work.
I use archlinux and evince flatpak.
Thanks you

**Comment by hadess** [comment]
Flatpaks don't export thumbnailers, so even if it was built, it wouldn't be usable.

See https://github.com/flatpak/flatpak/issues/4923
