### ISSUE TITLE
Non-prefixed filename org.gnome.evince.Daemon.service in app org.gnome.Evince, removing.

### ISSUE THREAD

**Issue by denniz-j** [flathub/org.gnome.Evince#26]
Issuing the following command...

    flatpak install https://flathub.org/repo/appstream/org.gnome.Evince.flatpakref
gives

    Installing: org.gnome.Evince/x86_64/stable
    Updating: org.gnome.Platform/x86_64/3.32 from flathub
    No updates.
    Updating: org.gnome.Platform.Locale/x86_64/3.32 from flathub
    No updates.
    Updating: org.freedesktop.Platform.html5-codecs/x86_64/18.08 from flathub
    No updates.
    Installing: org.gnome.Evince/x86_64/stable from org.gnome.Evince-4-origin

    1 metadata, 0 content objects fetched; 569 B transferred in 0 seconds   `
then, immediately, the following...

    (flatpak install:18526): flatpak-WARNING **: Non-prefixed filename  org.gnome.evince.Daemon.service in app org.gnome.Evince, removing.
    error: No such file or directory`
The system I'm on is Debian Stretch

    uname -a
    Linux a-Laptop 4.14.0-0.bpo.3-amd64 #1 SMP Debian 4.14.13-1~bpo9+1 (2018-01-14) x86_64 GNU/Linux
I've looked through previous issues here, but I'm not a programmer and I'm kinda lost at this point. Any suggestions would be appreciated.
thanks.

**Comment by TingPing** [comment]
Looks like upstream purposefully broke it: https://gitlab.gnome.org/GNOME/evince/commit/adc1fb72c8eca9e2bf9aaf905d9b645db6b2c0c9

cc @gpoo

**Comment by TingPing** [comment]
Also maybe @mvainola is interested in reverting that patch.

**Comment by TingPing** [comment]
Actually the comment here is correct: https://gitlab.gnome.org/GNOME/evince/merge_requests/98#note_341089

It should work if you have a modern `flatpak`.

I'd still say this situation is far from ideal and something needs renamed but we could just require a newer flatpak version to keep the package as-is.

**Comment by TingPing** [comment]
Oh Debian Stretch is oldstable which has Flatpak 0.8.

Install `flatpak` from `stretch-backports`.

**Comment by denniz-j** [comment]
Wow, extremely helpful, thanks @TingPing 
I didn't really understand the gitlab links, but the suggestion to install `flatpak` from `stretch-backports` did the trick, and I now have a shiny new `Evince/Document Viewer`, with thumbnails that don't disappear, etc.
