### ISSUE TITLE
Evince version 3.32.0 crashes when nested navigational outlines (pdf bookmarks) toggled shut

### ISSUE THREAD

**Issue by denniz-j** [flathub/org.gnome.Evince#28]
The following pdf document: [GNOME User Guide  (- openSUSE Leap 15.1)](https://doc.opensuse.org/documentation/leap/gnomeuser/book.gnomeuser_color_en.pdf)  contains nested navigational outlines, sometimes called pdf bookmarks (but different from the bookmarks created by Evince itself).  They are displayed in the side pane of Evince under the heading 'Outline'. 

With the above pdf file in Evince 3.32.0 in Flatpak version 1.2.4 when I click on the 'disclosure triangle icon' to fold or close a series of subheadings, or double click a heading to get the same effect, Evince crashes.
If I run Evince with the -v or -vv option, no information about the crash is displayed. All that is displayed is startup information. 

This does not seem to happen in the development version 3.33.0 of Evince. I installed this development version following the instructions about 'nightly' versions on this page: [A Beginners Guide To Flatpak (- by sk · updated May 2, 2019)](https://www.ostechnix.com/flatpak-new-framework-desktop-applications-linux/)

I have tried various different .pdf documents in various different versions of Evince, and in other .pdf viewers, but the crashing on closing a navigational outline heading only happens in Evince version 3.32.0 as described above.

If the development version 3.33.0 proves relatively stable I'm happy to keep using it. I just thought this behaviour in the stable version was worth reporting.

**Comment by jascrain** [comment]
It needs this commit - https://gitlab.gnome.org/GNOME/evince/commit/22ec59ab - there are a few bug fixes in evince's 3.32 branch, but there hasn't been a 3.32.1 release for them.

**Comment by angularorbit** [comment]
This happens to me too, I use Ubuntu 19.04, the pdf here [ The Linux Command Line ](https://tutorials.ubuntu.com/tutorial/command-line-for-beginners#8) by William Shotts.

**Comment by gpoo** [comment]
I updated the manifest to build Evince 3.32.1, which fixes the issue.
