### ISSUE TITLE
Opening print dialog in KDE leaves evince running in background after I close it.

### ISSUE THREAD

**Issue by ThanosApostolou** [flathub/org.gnome.Evince#31]
I'm using Kubuntu 19.10 with `xdg-desktop-portal-kde` installed. When I open a pdf with evince, after I open the print dialog I get this error:
```
(evince:2): Gtk-WARNING **: 15:58:59.949: GtkPrintOperation::create-custom-widget not supported with portal
```
Then after I close evince the app is still running on the background which leads to error if I try to open again the same file with evince:
```
Failed to Reload: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: org.freedesktop.DBus.Error.NameHasNoOwner
```

Is this a problem with the kde portal and should I report it there? Even if the kde portal is problematic is there any workaround so that evince exits cleanly when it's closed even with the 1st error?

**Comment by gpoo** [comment]
The problem is in Evince because it uses a custom dialog. The proper place to report it is https://gitlab.gnome.org/GNOME/evince/issues

**Comment by ThanosApostolou** [comment]
Ok, I reported here: https://gitlab.gnome.org/GNOME/evince/issues/1298
