### ISSUE TITLE
 Needs a screenshot

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.gnome.Evince#4]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by LeandroStanger** [comment]
@nedrichards could help

**Comment by nedrichards** [comment]
Filed upstream at https://gitlab.gnome.org/GNOME/evince/issues/907 I'm going to close it here as it needs to be fixed upstream (which I will look at helping out with)
