### ISSUE TITLE
Evince 3.26 flatpak fails to remember document zoom level, window size, location in doc etc

### ISSUE THREAD

**Issue by plrao72** [flathub/org.gnome.Evince#6]
The  Evince 3.26 flatpak on Debian 9 fails to remember the position in a  previously opened file as well as the zoom level, window size etc. These  are all attribute that the desktop version of Evince has no trouble  remembering.

---

Updated to the Evince 3.28 flatpak and the issue persists. When I reopen a file, I'm back at the first page with the default zoom level.

**Comment by nedrichards** [comment]
@gpoo what does evince use to remember this stuff? I think we might be missing a dbus permission here, or access to dconf somehow.

**Comment by gpoo** [comment]
dbus, gsettings/dconf (for saving global settins), and gio/gvfs for saving the metadata on each file.

When it does not have access, uses de memory backend, but that does not "remember" anything.

**Comment by nedrichards** [comment]
OK, I've added permissions for Evince to talk to gvfs, which it didn't have before. Hopefully that should fix things.
