### ISSUE TITLE
Text rendering issue (some font thing failed)

### ISSUE THREAD

**Issue by dsboger** [flathub/org.gnome.Evince#7]
When I open certain PDF documents Evince from flathub fails to render text. It works fine in a host-installed Evince, so I'm assuming it is some issue here. Also, I notice that Evince from flathub prints several stdout messages `some font thing failed` I'm attaching the offending document for testing (it is in public domain, so no redistribution issues).

[PPC-ADS-USJ-20180216.pdf](https://github.com/flathub/org.gnome.Evince/files/1864804/PPC-ADS-USJ-20180216.pdf)

**Comment by nedrichards** [comment]
I can no longer reproduce this after today's update to 3.28.2 and other flatpak changes using:
```
nick@endless-nedr:~$ flatpak info org.gnome.Evince
Ref: app/org.gnome.Evince/x86_64/stable
ID: org.gnome.Evince
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-07-15 03:35:08 +0000
Subject: Update to 3.28.2 and Poppler dependencies (4a715088)
Commit: 83bcfc0c65fd38d3f95dab46034c67fc9801f2fe3c3003e36e56726abd0bf865
Parent: f849df6554b13f6b16105686accbe4329aa2a514a4d4abf54fb6a07d3a43168f
Location: /var/lib/flatpak/app/org.gnome.Evince/x86_64/stable/83bcfc0c65fd38d3f95dab46034c67fc9801f2fe3c3003e36e56726abd0bf865
Installed size: 27.1 MB
Runtime: org.gnome.Platform/x86_64/3.28
```
Can you?

**Comment by dsboger** [comment]
It seems to be working fine now! I'm closing this.

Thank you!

**Comment by thalesmaoa** [comment]
It seems that the problem is back for TeXGyreHeros replacement. Generally used for Helvetica, Times-Roman, Times-Bold. No character are displayed.

![image](https://user-images.githubusercontent.com/14074573/139706297-00a60b9a-ef65-496c-86f7-5223a7b39096.png)
