### ISSUE TITLE
Flatpak isn't creating gnome desktop file

### ISSUE THREAD

**Issue by Zlopez** [flathub/org.gnome.Evince#8]
I tried to install evince from flathub. But after installation I noticed that the .desktop file for evince is missing.

**Comment by Zlopez** [comment]
I found the desktop file, but it is not shown in the gnome-shell search.
```
{zlopez zlopez-gamestation}/var/lib/flatpak/exports/share/applications> ls -l org.gnome.Evince.desktop
lrwxrwxrwx. 1 root root 95 May  1 17:42 org.gnome.Evince.desktop -> ../../../app/org.gnome.Evince/current/active/export/share/applications/org.gnome.Evince.desktop
{zlopez zlopez-gamestation}/var/lib/flatpak/exports/share/applications> ls -l ../../../app/org.gnome.Evince/current/active/export/share/applications/org.gnome.Evince.desktop
-rwxr-xr-x. 1 root root 13083 May  1 17:42 ../../../app/org.gnome.Evince/current/active/export/share/applications/org.gnome.Evince.desktop
```

I'm attaching the desktop file.
[org.gnome.Evince.desktop.tar.gz](https://github.com/flathub/org.gnome.Evince/files/1964426/org.gnome.Evince.desktop.tar.gz)

**Comment by TingPing** [comment]
If it is your first flatpak you will need to logout and back in.

**Comment by Zlopez** [comment]
I did a restart and still can't find it in gnome-shell search.

I don't have this issue with any other flatpak package I'm using.

**Comment by Zlopez** [comment]
I found out the Evince is not evince in gnome-shell search, but Document viewer.

I'm sorry for this misunderstanding and I'm closing the issue.
