### ISSUE TITLE
Problem with fonts (mathematical/Greek symbols)

### ISSUE THREAD

**Issue by rvlobato** [flathub/org.gnome.Evince#87]
Hi, the current version of evince on Flathub has a strange behavior. When one regenerate a pdf with latex, evince messes with the fonts (mathematical/Greek symbols) after reloading the file. Seems that the poppler update fixes it https://github.com/flathub/org.gnome.Evince/pull/86

Can someone please merger the update? Thanks

**Comment by evchimanski** [comment]
I'm facing a similar issue here. I've tried different fonts with no much success.
I would appreciate the merger as well. 

thank u

**Comment by rvlobato** [comment]
@evchimanski evince was updated, I'm closing this, feel free to open if having any issue.
